analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3521593,"name"\:"Cellphone Shop Trial \#3521593","teamId"\:3526522,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3520718,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3526522,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testreport.autoupload.manualstop.enable=false
