analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 1054564,\\n  \\"name\\"\: \\"Bions_Mobile\\",\\n  \\"teamId\\"\: 1040948,\\n  \\"organizationId\\"\: 1096488,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 1040948\\n}"
analytics.testresult.autosubmit=true
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
analytics.onpremise.enable=false
