<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign Out</name>
   <tag></tag>
   <elementGuidId>77236b32-8328-4fc6-8824-fef413c23fcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.unhover.w-100.btn.btn-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b627cb91-153e-4d66-9ce0-3567dfc2f391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5afc815e-fe60-42ea-9dae-a5e744263cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unhover w-100 btn btn-none</value>
      <webElementGuid>5b51a278-64a0-45b8-b95e-a1eff9dba00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Out</value>
      <webElementGuid>82fd2840-b855-48f7-925d-f8d859c83160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;layout_base&quot;]/main[@class=&quot;layout_base_body d-flex&quot;]/aside[@class=&quot;sidebar__shell&quot;]/div[@class=&quot;menu_setting open&quot;]/div[@class=&quot;menu_setting__bottom&quot;]/div[@class=&quot;p-3&quot;]/button[@class=&quot;unhover w-100 btn btn-none&quot;]</value>
      <webElementGuid>a990d1f9-3fb2-4093-aee2-f3de57fc6d03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>83ebeabd-fa1c-41e5-8444-46662de3df0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/aside/div/div[2]/div/button</value>
      <webElementGuid>8789a5ba-026b-46de-91df-2ba7c3672ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reconnect Times'])[1]/following::button[1]</value>
      <webElementGuid>002dd50c-01e2-48af-a2ba-a5ad4a06cdef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API Host'])[1]/following::button[1]</value>
      <webElementGuid>858c91a9-278c-4cf5-bbd9-b39af218faf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign Out']/parent::*</value>
      <webElementGuid>50300b78-48c9-44c4-aabf-b46208f298e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>aeb4b096-5a8e-4cd0-9e38-fff555436da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Sign Out' or . = 'Sign Out')]</value>
      <webElementGuid>625b54ff-b409-4155-82ed-8bd75a600e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
