<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign In_password</name>
   <tag></tag>
   <elementGuidId>6d65cdc3-2ef3-4fa1-87c7-ce4de3208b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0de87c0-22fd-483d-9554-ebad71470120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ea900ee7-16cc-454d-a71e-c7761b0892bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9df6506b-9189-4ce7-bae6-5ecbe62f2311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b799eb68-8455-4c4e-b12a-ea3158128169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2e1e192a-22ee-4755-8296-3fa085f1077a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>d1d6856b-1a3b-4c64-9d85-e0f0871b1ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;layout_base&quot;]/main[@class=&quot;layout_base_body d-flex&quot;]/article[@class=&quot;layout_base_body__container&quot;]/div[@class=&quot;login_feature&quot;]/div[@class=&quot;login_feature_form text-center&quot;]/div[@class=&quot;login_feature_form_body px-4&quot;]/form[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;position-relative pb-4&quot;]/input[@class=&quot;form-control form-control-lg&quot;]</value>
      <webElementGuid>4654e05b-41d2-480b-83cc-23c5b210f549</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>d76241dd-aafd-4514-b01e-290349e1649a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/article/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>1bfb2078-d5fb-4cad-8a02-4ffea8a6ee0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1bc89fe5-363c-4e9e-9868-9d16517bd993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password' and @name = 'password' and @type = 'password']</value>
      <webElementGuid>25a87fbb-df22-4912-bac2-346cfba6f1f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
