<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_menu</name>
   <tag></tag>
   <elementGuidId>70641939-aac0-40a1-84a0-8eef6b2cd180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.material-icons-outlined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/header/div[2]/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77fec876-0577-4be5-a29b-512626bf0424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons-outlined</value>
      <webElementGuid>fea9c4e3-388b-4909-8ce4-8854e88efaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>96fe56d7-57f7-4ad6-8753-91adac3a4888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;layout_base&quot;]/header[@class=&quot;header align-items-center&quot;]/div[@class=&quot;header_container justify-content-end&quot;]/div[@class=&quot;header_toolbar ps-3&quot;]/button[@class=&quot;button_icon menu__toggle  button_icon__secondary button_icon__md&quot;]/span[@class=&quot;material-icons-outlined&quot;]</value>
      <webElementGuid>1950ab46-40f6-4921-b0e5-7e1a5423e7c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/header/div[2]/div[2]/button/span</value>
      <webElementGuid>5babf3ae-8264-4eb9-a944-75f463c76faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dev Mode'])[1]/following::span[1]</value>
      <webElementGuid>09a130fb-6289-4efd-9ad7-6f05025f7023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::span[1]</value>
      <webElementGuid>d9f4507c-9b0f-4dfc-ba4a-aa9d73454afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/preceding::span[2]</value>
      <webElementGuid>0c2327cb-fb47-4e8b-b482-31c2b596a2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='menu']/parent::*</value>
      <webElementGuid>7226f592-a32d-4295-adc0-43b95f4932ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>b7dc078c-5b04-4636-a3b9-37205408eeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'menu' or . = 'menu')]</value>
      <webElementGuid>387efb9d-e610-4176-be02-1e9e21c2d0e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
