<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semantics_Login</name>
   <tag></tag>
   <elementGuidId>190ff5ed-0844-4d9e-bec7-a14afe548ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flt-semantic-node-20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-20']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>bf82c745-3f9b-4b98-8aae-c46e3a2d6627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-20</value>
      <webElementGuid>3635b845-cfa9-4216-b41d-ad657b6afc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d9ded3c-4175-4906-b530-78e346ff680b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d1b1f400-efc0-419a-97dd-adeeb8423350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>e724b23d-7a3a-46ee-8c5b-ec5fccfd636c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-semantic-node-20&quot;)</value>
      <webElementGuid>8f3626bd-afc5-4bf9-9754-dd8eb00430a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-20']</value>
      <webElementGuid>63c8562c-a02a-4202-99fc-0ef532067e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-2']/flt-semantics-container/flt-semantics[18]</value>
      <webElementGuid>d345c2ec-51ed-4bb1-aad9-617f79b2cf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password/PIN'])[1]/following::flt-semantics[1]</value>
      <webElementGuid>10925329-b97a-4e7d-a4f4-6f485eaead86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::flt-semantics[2]</value>
      <webElementGuid>f0a3faae-56c2-4795-a0b8-2a3ffebde250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Don’t have an account?'])[1]/preceding::flt-semantics[1]</value>
      <webElementGuid>34fa3a23-b936-48fd-b20a-b3417da9e72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V.0.1'])[1]/preceding::flt-semantics[2]</value>
      <webElementGuid>34bb9b26-299e-49d6-8306-e344b2617d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>dee7d6ae-9ed9-4b7c-8063-37eca70a578e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-semantics[18]</value>
      <webElementGuid>51ef36bd-18cd-4ab9-91b1-76a878baf712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id = 'flt-semantic-node-20' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>54619a38-c8da-4ab9-9c2b-6248ec738848</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
