<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1_2</name>
   <tag></tag>
   <elementGuidId>94d760b9-da92-4707-b7e4-6b0461f88204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flt-semantic-node-17 > input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-17']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5491efc-32e5-4636-829f-115e776619b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bacab586-457d-4b39-80dc-a5af308d204a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6f1b265d-e420-4a4a-aab9-cc0bf8a2e401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ccfc6ad9-e48d-4ff1-b128-43254b3a612c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-semantics-role</name>
      <type>Main</type>
      <value>text-field</value>
      <webElementGuid>c9f7d161-cf42-48e2-979f-b090d1cf88c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter PIN</value>
      <webElementGuid>5e397b0b-096e-47e2-b942-8e57b57cbbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-semantic-node-17&quot;)/input[1]</value>
      <webElementGuid>d117f5f1-1bbc-4c0d-a061-f91440fbb1e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-17']/input</value>
      <webElementGuid>9af43a2d-f305-4fa6-b6fb-e991e5598cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-semantics[15]/input</value>
      <webElementGuid>67cadca6-fc76-4e5a-84a7-681377bbd9c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
